# Generated by Django 2.2.6 on 2019-11-04 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tarefa_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meta',
            name='prazo',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
